package com.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.telit.money.start.bean.AdviceBean;

import com.greendao.dao.AdviceBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig adviceBeanDaoConfig;

    private final AdviceBeanDao adviceBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        adviceBeanDaoConfig = daoConfigMap.get(AdviceBeanDao.class).clone();
        adviceBeanDaoConfig.initIdentityScope(type);

        adviceBeanDao = new AdviceBeanDao(adviceBeanDaoConfig, this);

        registerDao(AdviceBean.class, adviceBeanDao);
    }
    
    public void clear() {
        adviceBeanDaoConfig.clearIdentityScope();
    }

    public AdviceBeanDao getAdviceBeanDao() {
        return adviceBeanDao;
    }

}
